name: main
on: push

jobs:
  build_oidc_2_0_image:
    runs-on: k3s-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.nextpertise.tools
          username: ${{ secrets.REGISTRY_NEXTPERTISE_TOOLS_ACCOUNT }}
          password: ${{ secrets.REGISTRY_NEXTPERTISE_TOOLS_KEY }}

      - name: Set context
        run: echo "context=$(pwd)" >> $GITHUB_ENV

      - name: Push image to registry
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: ${{ env.context }}/
          push: true
          tags: |
            registry.nextpertise.tools/nextpertise/kong-plugin-oidc:2.0
          build-args: kong_version=2.0


  build_oidc_2_5_image:
    runs-on: k3s-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.nextpertise.tools
          username: ${{ secrets.REGISTRY_NEXTPERTISE_TOOLS_ACCOUNT }}
          password: ${{ secrets.REGISTRY_NEXTPERTISE_TOOLS_KEY }}

      - name: Set context
        run: echo "context=$(pwd)" >> $GITHUB_ENV

      - name: Push image to registry
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: ${{ env.context }}/
          push: true
          tags: |
            registry.nextpertise.tools/nextpertise/kong-plugin-oidc:2.5
            registry.nextpertise.tools/nextpertise/kong-plugin-oidc:rc
          build-args: kong_version=2.5